name: Frontend CI

on:
  push:
    paths:
      - 'app/frontend/**'  # Trigger only when changes are made in the frontend directory
  pull_request:
    paths:
      - 'app/frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install frontend dependencies
        run: npm install
        working-directory: app/frontend

      - name: Build Frontend Docker image
        run: docker build -t mshallom/app:latest .
        working-directory: app/frontend

      - name: Push Docker image
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push mshallom/app:latest
        env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
